const migStart = {
    product_template: 'overwrite target data by source data',
    account_move: 'overwrite target data by source data',
    pos_order: 'overwrite target data by source data',
    sale_order_line: 'overwrite target data by source data',
    res_partner: 'overwrite target data by source data',
    product_product: 'overwrite target data by source data',
    sale_order:'overwrite target data by source data',
    ir_model_data: 'Keep target data, do not migrate from source',
    purchase_order: 'overwrite target data by source data',
    stock_picking_type: 'overwrite target data by source data',
    product_attribute: 'overwrite target data by source data',
    payment_provider: 'Keep target data, do not migrate from source',
    res_company: 'overwrite target data by source data',
    res_config_settings: 'Keep target data, do not migrate from source',
    pos_config: 'Keep target data, do not migrate from source',
    account_account: 'overwrite target data by source data',
    account_account_account_tag: 'overwrite target data by source data',
    account_account_tag: 'overwrite target data by source data',
    account_account_tag_account_move_line_rel: 'keep target data, do not migrate from source',
    account_account_tag_account_tax_repartition_line_rel: 'keep target data, do not migrate from source',
    account_analytic_plan: 'overwrite target data by source data',
    account_bank_statement_line: 'overwrite target data by source data',
    account_cash_rounding: 'overwrite target data by source data',
    account_fiscal_position: 'Keep target data, do not migrate from source',
    account_full_reconcile: 'keep target data, do not migrate from source',
    account_group: 'keep target data, do not migrate from source',
    account_incoterms: 'keep target data, do not migrate from source',
    account_invoice_transaction_rel: 'overwrite target data by source data',
    account_journal: 'keep target data, do not migrate from source',
    account_move_line: 'overwrite target data by source data',
    account_move_line_account_tax_rel: 'overwrite target data by source data',
}
export default migStart;